services:
  info-agent-service:
    build: .
    container_name: info-agent-service
    ports:
      - "5015:5015"
    env_file:
      - .env
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - TEXT_EMBEDDING_MODEL=${TEXT_EMBEDDING_MODEL}
      - NOMIC_API_KEY=${NOMIC_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 5015
    restart: unless-stopped
