services:
  # === Kong Gateway ===
  kong:
    image: kong:3.4
    container_name: kong-gateway
    env_file:
      - .env
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_VAULT_CONFIGURATION_RESOLVE=on
      - KONG_VAULT_ENV_PREFIX=KONG_VAR_
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8002:8002" # Admin GUI
    restart: always

include:
  # === News Scraper Microservice ===
  - path: ./news-scraper/docker-compose.yml
    env_file: ./news-scraper/.env
    project_directory: ./news-scraper

  # === Preprocessing Service Microservice ===
  - path: ./preprocessing-service/docker-compose.yml
    env_file: ./preprocessing-service/.env
    project_directory: ./preprocessing-service

  # === Ticker Identification Service Microservice ===
  - path: ./ticker-identification-service/docker-compose.yml
    env_file: ./ticker-identification-service/.env
    project_directory: ./ticker-identification-service

  # === Event Identification Service Microservice ===
  - path: ./event-identification-service/docker-compose.yml
    env_file: ./event-identification-service/.env
    project_directory: ./event-identification-service

  # === Sentiment Analysis Service Microservice ===
  - path: ./sentiment-analysis-service/docker-compose.yml
    env_file: ./sentiment-analysis-service/.env
    project_directory: ./sentiment-analysis-service

  # === User Info Microservice ===
  - path: ./user-info/docker-compose.yml
    env_file: ./user-info/.env
    project_directory: ./user-info

  # === RAG Chatbot Microservice ===
  - path: ./rag-chatbot/docker-compose.yml
    env_file: ./rag-chatbot/.env
    project_directory: ./rag-chatbot

  # === Trading Agent M Microservice ===
  - path: ./trading-agent-m/docker-compose.yml
    env_file: ./trading-agent-m/.env
    project_directory: ./trading-agent-m

  # === Trading Service Microservice ===
  - path: ./trading-service/docker-compose.yml
    env_file: ./trading-service/.env
    project_directory: ./trading-service

  # === Notification Alert Service Microservice ===
  - path: ./notification-alert/docker-compose.yml
    env_file: ./notification-alert/.env
    project_directory: ./notification-alert

  # === Trading Agent M Microservice ===
  - path: ./news-aggregator-service/docker-compose.yml
    env_file: ./news-aggregator-service/.env
    project_directory: ./news-aggregator-service

  # === Qdrant Retrieval Microservice ===
  - path: ./qdrant-retrieval/docker-compose.yml
    env_file: ./qdrant-retrieval/.env
    project_directory: ./qdrant-retrieval

  # === News Scraper TradingView Microservice ===
  - path: ./news-scraper-tradingview/docker-compose.yml
    env_file: ./news-scraper-tradingview/.env
    project_directory: ./news-scraper-tradingview

  # === Metrics Tracker Microservice ===
  - path: ./metrics-tracker/docker-compose.yml
    env_file: ./metrics-tracker/.env
    project_directory: ./metrics-tracker

