services:
  redis:
    image: redis:7-alphine
    container_name: redis-queue
    ports:
      - "6379:6379"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

  news-analysis-service:
    build: .
    container_name: news-analysis-container
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    environment:
      - QDRANT_HOST=qdrant
      - REDIS_URL=redis://redis:6379
      - REDIS_QUEUE_NAME=raw_news_queue
    depends_on:
      - qdrant
    command: fastapi dev app/main.py --host 0.0.0.0 --port 5002
