services:
  metrics-tracker:
    build: .
    container_name: metrics-tracker-container
    env_file:
      - .env
    ports:
      - "5014:5014"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_BUCKET_ACCESS_KEY=${AWS_BUCKET_ACCESS_KEY}
      - AWS_BUCKET_SECRET=${AWS_BUCKET_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    command: uvicorn app.main:app --host 0.0.0.0 --port 5014
    restart: unless-stopped
