apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-agent-m-ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/v1/rag
            pathType: Prefix
            backend:
              service:
                name: trading-agent-m
                port:
                  number: 8080
