apiVersion: v1
kind: Service
metadata:
  name: trading-agent-m-service
  labels:
    app: trading-agent-m
spec:
  selector:
    app: trading-agent-m
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
