name: Continuous Integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  go-tests:
    name: Go Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.x"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Verify Binary Compilation
        run: go build -v -o app ./cmd/main.go
