replicaCount: 2

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/qdrant-retrieval
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5009
  targetPort: 5009

startupProbe:
  httpGet:
    path: /
    port: 5009
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5009
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5009
  initialDelaySeconds: 5
  periodSeconds: 10

worker:
  enabled: true
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  command: ["python", "-m", "app.services.qdrant_vectorisation_worker"]

secretName: qdrant-retrieval-secrets

ingress:
  enabled: true
  public:
    enabled: true
    paths:
      - path: /api/v1/qdrant/healthcheck
        pathType: Exact
  protected:
    enabled: true
    paths:
      - path: /api/v1/qdrant
        pathType: Prefix
