services:
  event-identification-api:
    build: .
    container_name: event-identification-api-container
    env_file:
      - .env
    ports:
      - "5011:5011"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TICKER_STREAM=${TICKER_STREAM}
      - EVENT_STREAM=${EVENT_STREAM}
      - LARGE_LANGUAGE_MODEL_GROQ=${LARGE_LANGUAGE_MODEL_GROQ}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AWS_BUCKET_ACCESS_KEY=${AWS_BUCKET_ACCESS_KEY}
      - AWS_BUCKET_SECRET=${AWS_BUCKET_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - EVENTS_KEY=${EVENTS_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 5011
    restart: unless-stopped

  event-identification-worker:
    build: .
    container_name: event-identification-worker-container
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TICKER_STREAM=${TICKER_STREAM}
      - EVENT_STREAM=${EVENT_STREAM}
      - LARGE_LANGUAGE_MODEL_GROQ=${LARGE_LANGUAGE_MODEL_GROQ}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AWS_BUCKET_ACCESS_KEY=${AWS_BUCKET_ACCESS_KEY}
      - AWS_BUCKET_SECRET=${AWS_BUCKET_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - EVENTS_KEY=${EVENTS_KEY}
    command: python -m app.services.event_identification_worker
    restart: unless-stopped