services:
  news-scraper-service:
    build: .
    env_file:
      - .env
    container_name: news-scraper
    ports:
      - "5003:5003"
    volumes:
      - .:/code
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_STREAM=${REDIS_STREAM}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: uvicorn app.main:app --host 0.0.0.0 --port 5003
    restart: always
