services:
  reddit-stream-service:
    build: .
    container_name: reddit-stream
    volumes:
      - .:/code
    env_file: 
      - .env
    command: python app/main.py stream
    restart: unless-stopped

  reddit-batch-service:
    build: .
    container_name: reddit-batch
    volumes:
      - .:/code
    env_file: 
      - .env
    environment:
    - PYTHONUNBUFFERED=1
    command: python app/main.py batch
    restart: "no"

