replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/rag-chatbot
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5004
  targetPort: 5004

startupProbe:
  httpGet:
    path: /healthcheck
    port: 5004
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 5004
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /healthcheck
    port: 5004
  initialDelaySeconds: 5
  periodSeconds: 10

secretName: notification-alert-secrets
