replicaCount: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/news-aggregator-service
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5008
  targetPort: 5008

startupProbe:
  httpGet:
    path: /
    port: 5008
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5008
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5008
  initialDelaySeconds: 5
  periodSeconds: 10

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "5008"
  prometheus.io/path: "/metrics"

secretName: news-aggregator-service-secrets

ingress:
  enabled: true
  public:
    enabled: true
    paths:
      - path: /api/v1/news-aggregator/healthcheck
        pathType: Exact
      - path: /api/v1/news-aggregator/metrics
        pathType: Exact
  protected:
    enabled: true
    paths:
      - path: /api/v1/news-aggregator
        pathType: Prefix

