replicaCount: 2

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/user-info
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 8080
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 8080
  initialDelaySeconds: 30

secretName: user-info-secrets
