replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/news-scraper-tradingview
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5013
  targetPort: 5013

startupProbe:
  httpGet:
    path: /
    port: 5013
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5013
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5013
  initialDelaySeconds: 5
  periodSeconds: 10F

secretName: news-scraper-tradingview-secrets
