replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/trading-agent-m
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5006
  targetPort: 5006

startupProbe:
  httpGet:
    path: /
    port: 5006
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5006
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5006
  initialDelaySeconds: 5
  periodSeconds: 10

secretName: trading-agent-m-secrets

ingress:
  enabled: true
  public:
    enabled: true
    paths:
      - path: /api/v1/agent-m/healthcheck
        pathType: Exact
  protected:
    enabled: true
    paths:
      - path: /api/v1/agent-m
        pathType: Prefix

