replicaCount: 2

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/news-analysis
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5002
  targetPort: 5002

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 5002
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 5002
  initialDelaySeconds: 30

secretName: news-analysis-secrets
