replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/notification-alert
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5004
  targetPort: 5004

startupProbe:
  httpGet:
    path: /
    port: 5004
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5004
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5004
  initialDelaySeconds: 5
  periodSeconds: 10

secretName: notification-alert-secrets

ingress:
  enabled: true
  public:
    enabled: true
    paths:
      - path: /api/v1/notification/healthcheck
        pathType: Exact
  protected:
    enabled: true
    paths:
      - path: /api/v1/notification
        pathType: Prefix

