replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/trading-service
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5007
  targetPort: 5007

livenessProbe:
  httpGet:
    path: /
    port: 5007
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /
    port: 5007
  initialDelaySeconds: 30

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "5007"
  prometheus.io/path: "/metrics"

secretName: trading-service-secrets

ingress:
  enabled: true
  public:
    enabled: true
    paths:
      - path: /api/v1/trading/healthcheck
        pathType: Exact
      - path: /api/v1/trading/metrics
        pathType: Exact
  protected:
    enabled: true
    paths:
      - path: /api/v1/trading
        pathType: Prefix

