replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/user-info
  tag: v1
  pullPolicy: Always

volumeMounts:
  - name: rds-cert-volume
    mountPath: /certs
    readOnly: true

volumes:
  - name: rds-cert-volume
    configMap:
      name: rds-certs

service:
  type: ClusterIP
  port: 5005
  targetPort: 5005

livenessProbe:
  httpGet:
    path: /
    port: 5005
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /
    port: 5005
  initialDelaySeconds: 30

secretName: user-info-secrets
