replicaCount: 1

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/sentiment-analysis-service
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5012
  targetPort: 5012

startupProbe:
  httpGet:
    path: /
    port: 5012
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5012
  initialDelaySeconds: 60

readinessProbe:
  httpGet:
    path: /
    port: 5012
  initialDelaySeconds: 30

worker:
  enabled: true
  command: ["python", "-m", "app.services.sentiment_analysis_worker"]

secretName: sentiment-analysis-secrets
