replicaCount: 1

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/metrics-tracker
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5014
  targetPort: 5014

startupProbe:
  httpGet:
    path: /
    port: 5014
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 5014
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 5014
  initialDelaySeconds: 5
  periodSeconds: 10

secretName: metrics-tracker-secrets
