replicaCount: 2

image:
  repository: 182138814885.dkr.ecr.us-east-1.amazonaws.com/rag-chatbot
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 5001
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 5001
  initialDelaySeconds: 30

secretName: rag-chatbot-secrets
