services:
  rag-bot-conversation-db:
      image: postgres:16-alpine
      container_name: rag-bot-conversation-db
      restart: always
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  rag-chatbot-service:
    build: .
    env_file:
      - .env
    container_name: rag-agentic-app
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LARGE_LANGUAGE_MODEL=${LARGE_LANGUAGE_MODEL}
      - TEMPERATURE=${TEMPERATURE}
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - MAX_COMPLETION_TOKEN=${MAX_COMPLETION_TOKEN}
      - QDRANT_RETRIEVAL_QUERY_URL=${QDRANT_RETRIEVAL_QUERY_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_FILE_NAME=${AWS_S3_FILE_NAME}

      - FORCE_COLOR=true
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 5001
    restart: unless-stopped

volumes:
  postgres_data: