services:
  notification-service:
    build: .
    container_name: notification-service
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "5004:5004"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
