services:
  user-info-service:
    build: .
    env_file:
      - .env
    volumes:
      - ../certs:/certs
    container_name: user-module
    ports:
      - "8080:8080"
    environment:
      - HOST=${HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - DB_SSL_ROOT_CERT=${DB_SSL_ROOT_CERT}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_EXPIRATION_HOURS=${CACHE_EXPIRATION_HOURS}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - X_KEY=${X_KEY}
      - X_SECRET=${X_SECRET}
      - X_CALL_BACK=${X_CALL_BACK}
      - X_REDIRECT_FRONTEND=${X_REDIRECT_FRONTEND}
    restart: unless-stopped
