services:
  user-postgres-db:
    image: postgres:15-alpine
    container_name: user-module-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-cache-user-info
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  user-service:
    build: .
    container_name: user-module
    ports:
      - "8080:8080"
    environment:
      - HOST=user-postgres-db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_EXPIRATION_HOURS=${CACHE_EXPIRATION_HOURS}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - X_KEY=${X_KEY}
      - X_SECRET=${X_SECRET}
      - X_CALL_BACK=${X_CALL_BACK}
      - X_REDIRECT_FRONTEND=${X_REDIRECT_FRONTEND}
    depends_on:
      user-postgres-db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
