name: Event Identification Service CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["event-identification-service/**"]
  pull_request:
    branches: ["master"]
    paths: ["event-identification-service/**"]

jobs:
  event-identification-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "event-identification-service"
      cluster-name: "agentic-m-cluster"
      image-name: "event-identification-service"
      values-file: "deploy/values-event-identification.yaml"
      secret-key: "EVENT_IDENTIFICATION_SECRETS"
    secrets: inherit
