on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
      - "info-agent-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["dev"]
    paths:
      - "info-agent-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  info-agent-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "info-agent-service"
      cluster-name: "agentic-m-cluster"
      image-name: "info-agent-service"
      values-file: "deploy/prod/values-info-agent.yaml"
      secret-key: "INFO_AGENT_SECRETS"
    secrets: inherit
