name: Info Agent Service CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      skip-approval:
        description: "Bypass manual approval"
        required: false
        default: "false"
  push:
    branches: ["master", "dev"]
    paths:
      - "info-agent-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "info-agent-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  info-agent-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "info-agent-service"
      cluster-name: "agentic-m-cluster"
      image-name: "info-agent-service"
      skip-approval: ${{ inputs.skip-approval || 'false' }}
      values-file: "deploy/prod/values-info-agent.yaml"
      secret-key: "INFO_AGENT_SECRETS"
    secrets: inherit