name: Metrics Tracker Service CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
  pull_request:
    branches: ["dev"]
    paths:

jobs:
  metrics-tracker-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "metrics-tracker"
      cluster-name: "agentic-m-cluster"
      image-name: "metrics-tracker-service"
      values-file: "deploy/prod/values-metrics-tracker.yaml"
      secret-key: "METRICS_TRACKER_SECRETS"
    secrets: inherit
