name: Metrics Tracker Service CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["metrics-tracker/**"]
  pull_request:
    branches: ["master"]
    paths: ["metrics-tracker/**"]

jobs:
  metrics-tracker-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "metrics-tracker-service"
      cluster-name: "agentic-m-cluster"
      image-name: "metrics-tracker-service"
      values-file: "deploy/values-metrics-tracker.yaml"
      ingress-path: "deploy/ingress.yaml"
      secret-key: "METRICS_TRACKER_SECRETS"
    secrets: inherit
