name: News Aggregator CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
      - "news-aggregator-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["dev"]
    paths:
      - "news-aggregator-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  news-aggregator-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "news-aggregator-service"
      cluster-name: "agentic-m-cluster"
      image-name: "news-aggregator-service"
      values-file: "deploy/prod/values-news-aggregator.yaml"
      secret-key: "NEWS_AGGREGATOR_SECRETS"
    secrets: inherit