name: News Aggregator CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["news-aggregator-service/**"]
  pull_request:
    branches: ["master"]
    paths: ["news-aggregator-service/**"]

jobs:
  news-aggregator-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "news-aggregator-service"
      cluster-name: "agentic-m-cluster"
      image-name: "news-aggregator-service"
      values-file: "deploy/values-news-aggregator.yaml"
      ingress-path: "deploy/ingress.yaml"
      secret-key: "NEWS_AGGREGATOR_SECRETS"
    secrets: inherit
