on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
      - "notification-alert/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["dev"]
    paths:
      - "notification-alert/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  notification-alert-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "notification-alert"
      cluster-name: "agentic-m-cluster"
      image-name: "notification-alert"
      values-file: "deploy/prod/values-notification-alert.yaml"
      secret-key: "NOTIFICATION_ALERT_SECRETS"
    secrets: inherit
