name: Notification Alert CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      skip-approval:
        description: "Bypass manual approval"
        required: false
        default: "false"
  push:
    branches: ["master", "dev"]
    paths:
      - "notification-alert/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "notification-alert/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  notification-alert-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "notification-alert"
      cluster-name: "agentic-m-cluster"
      image-name: "notification-alert"
      skip-approval: ${{ inputs.skip-approval || 'false' }}
      values-file: "deploy/prod/values-notification-alert.yaml"
      secret-key: "NOTIFICATION_ALERT_SECRETS"
    secrets: inherit