name: Notification Alert  CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["notification-alert/**"]
  pull_request:
    branches: ["master"]
    paths: ["notification-alert/**"]

jobs:
  notification-alert-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "notification-alert"
      cluster-name: "agentic-m-cluster"
      image-name: "notification-alert"
      values-file: "deploy/prod/values-notification-alert.yaml"
      secret-key: "NOTIFICATION_ALERT_SECRETS"
    secrets: inherit
