on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
      - "preprocessing-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["dev"]
    paths:
      - "preprocessing-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  preprocessing-service-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "preprocessing-service"
      cluster-name: "agentic-m-cluster"
      image-name: "preprocessing-service"
      values-file: "deploy/prod/values-pre-processing.yaml"
      secret-key: "PREPROCESSING_SERVICE_SECRETS"
    secrets: inherit
