name: Preprocessing Service CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["preprocessing-service/**"]
  pull_request:
    branches: ["master"]
    paths: ["preprocessing-service/**"]

jobs:
  preprocessing-service-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "preprocessing-service"
      cluster-name: "agentic-m-cluster"
      image-name: "preprocessing-service"
      values-file: "deploy/prod/values-pre-processing.yaml"
      secret-key: "PREPROCESSING_SERVICE_SECRETS"
    secrets: inherit
