name: RAG Chatbot CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      skip-approval:
        description: "Bypass manual approval"
        required: false
        default: "false"
  push:
    branches: ["master", "dev"]
    paths:
      - "rag-chatbot/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "rag-chatbot/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  rag-bot-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "rag-chatbot"
      cluster-name: "agentic-m-cluster"
      image-name: "rag-chatbot"
      skip-approval: ${{ inputs.skip-approval || 'false' }}
      values-file: "deploy/prod/values-chatbot.yaml"
      secret-key: "RAG_CHATBOT_SECRETS"
    secrets: inherit