name: RAG Chatbot CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["rag-chatbot/**"]
  pull_request:
    branches: ["master"]
    paths: ["rag-chatbot/**"]

jobs:
  rag-bot-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "rag-chatbot"
      cluster-name: "agentic-m-cluster"
      image-name: "rag-chatbot"
      values-file: "deploy/values-chatbot.yaml"
      secret-key: "RAG_CHATBOT_SECRETS"
    secrets: inherit
