name: Ticker Identification Service CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
      - "ticker-identification-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "ticker-identification-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  ticker-identification-service-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "ticker-identification-service"
      cluster-name: "agentic-m-cluster"
      image-name: "ticker-identification-service"
      values-file: "deploy/prod/values-ticker-identification.yaml"
      secret-key: "TICKER_IDENTIFICATION_SECRETS"
    secrets: inherit