name: Trading Agent M CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["master", "dev"]
    paths:
  pull_request:
    branches: ["dev"]
    paths:

jobs:
  trading-agent-m-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "trading-agent-m"
      cluster-name: "agentic-m-cluster"
      image-name: "trading-agent-m"
      values-file: "deploy/prod/values-trading-agent-m.yaml"
      secret-key: "TRADING_AGENT_M_SECRETS"
    secrets: inherit
