name: Trading Service CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      skip-approval:
        description: "Bypass manual approval"
        required: false
        default: "false"
  push:
    branches: ["master", "dev"]
    paths:
      - "trading-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "trading-service/**"
      - "deploy/**"
      - "infra/**"
      - ".github/workflows/python-reusable-workflow.yaml"
jobs:
  trading-service-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yaml
    with:
      working-directory: "trading-service"
      cluster-name: "agentic-m-cluster"
      image-name: "trading-service"
      skip-approval: ${{ inputs.skip-approval || 'false' }}
      values-file: "deploy/prod/values-trading-service.yaml"
      secret-key: "TRADING_SERVICE_SECRETS"
    secrets: inherit